### PR TITLE
Update urls as rrmj version updated

### PR DESCRIPTION
**Pull request by wilsonwen**

### CODE REVIEW

**Comment by taxigps** [comment]
@jindaxia

**Comment by jindaxia** [comment]
最近太忙，没实际测试

**Comment by jindaxia** [comment]
@wilsonwen @taxigps  https://github.com/jindaxia/plugin.video.rrmj/tree/v0.2.0 
merged and fix the new api

**Comment by taxigps** [comment]
updated. thanks!

**Pull request closed without merging**
