### PR TITLE
add haidao video plugin.

### PR DESCRIPTION
**Pull request by malimaliao**
提交一个新视频插件 haidao

### CODE REVIEW

**Comment by malimaliao** [comment]
test or use, download and install to Kodi via this link:[download](https://github.com/malimaliao/plugin.video.haidao/releases/).
PS. choose to use ZIP installation.

**Comment by taxigps** [comment]
这是个成人站点的插件吗？本项目不支持成人内容分发。

**Comment by malimaliao** [comment]
no,
18+ is blocked.
Variables Blacklist keywords: close_keyword

**Comment by taxigps** [comment]
感谢分享

**Pull request merged**
