### PR TITLE
[plugin.video.cntv-live] update to v2.0.4

### PR DESCRIPTION
**Pull request by RunasSudo**
- Integrate with Live IPTV XMLTV functionality.
- Add English translations of main menu pindao items.

### CODE REVIEW

**Comment by cmeng-git** [comment]
Hi Runas,

Do not known what has changed since the earlier release of the cntv-live video plugin..
In the initial releases, I was able to watch almost all the CCTV and Provincial channels, and the streaming latency was very fast.

However in the latest release v2.0.6, I am facing with the same error messages "Channel has no HLS stream" for almost all the channels I tried to watch. For those channels that I can watch, the video streaming were slow and pause frequently (every few seconds). 

Is there some plugin setting I can change to help overcome the problem.
I am accessing the CNTV-Live from Singapore.
Thanks.

**Comment by cmeng-git** [comment]
Hi,
Thanks for the clarifications.

**Comment by cmeng-git** [comment]
Hi,

Did you manage to fix the problem of CNTV streaming?

I have version 2.0.8 install on Kodi, however I am unable to access to any of the CNTV channels
It always shows "Channel unavailable" on every channel I try to access. I am accessing CNTV from Singapore. Are CNTV blocked users from oversea access?

**Comment by RunasSudo** [comment]
Have you tried CCTV1? Other channels often don't work, but CCTV1 works for me. If it's still not working, can you post the contents of **kodi.log** and/or the contents of **http://vdn.live.cntv.cn/api2/live.do?channel=pa://cctv_p2p_hdcctv1** ?

**Comment by cmeng-git** [comment]
I am using kodi-helix latest release:
After I clicked the CNTV-1, the following log text is added.

11:40:21 T:8208  NOTICE: Thread JobWorker start, auto delete: true
11:40:22 T:8848  NOTICE: Thread LanguageInvoker start, auto delete: false
11:40:22 T:8848  NOTICE: -->Python Interpreter Initialized<--
11:40:22 T:8848 WARNING: Attempt to use invalid handle -1

------------------------------------
content of http://vdn.live.cntv.cn/api2/live.do?channel=pa://cctv_p2p_hdcctv1
{
hls_url: {
hls4: "http://ak.live.cntv.cn/i/cctv1dvr_1@167344/master.m3u8?AUTH=ip%3D42.60.118.240%7Est%3D1424575987%7Eexp%3D1424662387%7Eacl%3D%2F*%7Ehmac%3Db480fb0ff860582f1183bd5253d8a3e5fc4e8dc8a4c82cb4a721fa4d8e0d68bc",
hls3: "http://ak.live.cntv.cn/i/cctv1_1@108430/master.m3u8?b=100-300&AUTH=ip%3D42.60.118.240%7Est%3D1424575987%7Eexp%3D1424662387%7Eacl%3D%2F*%7Ehmac%3Db480fb0ff860582f1183bd5253d8a3e5fc4e8dc8a4c82cb4a721fa4d8e0d68bc",
hls5: "http://vpic.cntv.cloudcdn.net:8000/live/pic/channel14",
hls2: "http://ak.live.cntv.cn/i/cctv1_1@108430/master.m3u8?b=300-500&AUTH=ip%3D42.60.118.240%7Est%3D1424575987%7Eexp%3D1424662387%7Eacl%3D%2F*%7Ehmac%3Db480fb0ff860582f1183bd5253d8a3e5fc4e8dc8a4c82cb4a721fa4d8e0d68bc",
hls1: "http://ak.live.cntv.cn/i/cctv1_1@108430/master.m3u8?AUTH=ip%3D42.60.118.240%7Est%3D1424575987%7Eexp%3D1424662387%7Eacl%3D%2F*%7Ehmac%3Db480fb0ff860582f1183bd5253d8a3e5fc4e8dc8a4c82cb4a721fa4d8e0d68bc"
},
hds_url: {
hds1: "http://ak.live.cntv.cn/z/cctv1_1@108430/manifest.f4m?AUTH=ip%3D42.60.118.240%7Est%3D1424575987%7Eexp%3D1424662387%7Eacl%3D%2F*%7Ehmac%3Db480fb0ff860582f1183bd5253d8a3e5fc4e8dc8a4c82cb4a721fa4d8e0d68bc",
hds2: "http://ak.live.cntv.cn/z/cctv1dvr_1@167344/manifest.f4m?AUTH=ip%3D42.60.118.240%7Est%3D1424575987%7Eexp%3D1424662387%7Eacl%3D%2F*%7Ehmac%3Db480fb0ff860582f1183bd5253d8a3e5fc4e8dc8a4c82cb4a721fa4d8e0d68bc",
hds3: "",
hds4: "",
hds5: ""
},
hls_cdn_info: {
cdn_code: "LIVE-HLS-CDN-AK",
cdn_name: "3rdAkamai"
},
client_sid: "98b03ff8298b4054bed520070baf80f1",
ack: "yes",
flv_cdn_info: {
cdn_code: "LIVE-FLV-CDN-AK",
cdn_name: "3rdAkamai"
},
hds_cdn_info: {
cdn_code: "LIVE-HDS-CDN-AK",
cdn_name: "3rdAkamai"
},
lc: {
isp_code: "10",
city_code: "",
provice_code: "",
country_code: "SG",
ip: "42.60.118.240"
},
flv_url: {
flv2: "http://ak.live.cntv.cn/z/cctv1_1@108430/manifest.f4m?AUTH=ip%3D42.60.118.240%7Est%3D1424575987%7Eexp%3D1424662387%7Eacl%3D%2F*%7Ehmac%3Db480fb0ff860582f1183bd5253d8a3e5fc4e8dc8a4c82cb4a721fa4d8e0d68bc",
flv3: "",
flv1: "http://ak.live.cntv.cn/z/cctv1_1@108430/manifest.f4m?AUTH=ip%3D42.60.118.240%7Est%3D1424575987%7Eexp%3D1424662387%7Eacl%3D%2F*%7Ehmac%3Db480fb0ff860582f1183bd5253d8a3e5fc4e8dc8a4c82cb4a721fa4d8e0d68bc",
flv4: "http://ak.live.cntv.cn/i/cctv1dvr_1@167344/master.m3u8?AUTH=ip%3D42.60.118.240%7Est%3D1424575987%7Eexp%3D1424662387%7Eacl%3D%2F*%7Ehmac%3Db480fb0ff860582f1183bd5253d8a3e5fc4e8dc8a4c82cb4a721fa4d8e0d68bc",
flv5: "http://vpub.cntv.cloudcdn.net/cache/14_/channel.pub?AUTH=ip%3D42.60.118.240%7Est%3D1424575987%7Eexp%3D1424662387%7Eacl%3D%2F*%7Ehmac%3Db480fb0ff860582f1183bd5253d8a3e5fc4e8dc8a4c82cb4a721fa4d8e0d68bc"
},
public: "1"
}

**Comment by cmeng-git** [comment]
from http://vdn.live.cntv.cn/api2/live.do?channel=pa://cctv_p2p_hdcctv1
If i click on the hds_url or flv_url links, I may receive the following access deny
But hls_url seems ok with *.m3u8 file for download

----------------------
Access Denied

You don't have permission to access "http://ak.live.cntv.cn/z/cctv1_1@108430/manifest.f4m?" on this server.
Reference #18.5ec7387d.1424577420.4dc55604

**Comment by RunasSudo** [comment]
Hmm... That log and live.do content looks normal to me, but the 'Channel unavailable' message has me stumped. Are you sure there's no other information in the log file? What does the progress bar do when you try to load the video? Does it fail after the first 'Trying 1.2.3.4 (HLS)' or does it keep going?

**Comment by RunasSudo** [comment]
Can you try replace lines 94 (`tries = 0`) to 118 (`print(traceback.format_exc())`) with:

    hostname = tmphostname
    url = tmpurl

**Comment by cmeng-git** [comment]
Without the code change;
The dialog shows "getting channel info" and immediate fall through to "Channel unavailable" error message.
There is no attempt to load streaming data .
Note: Debug shows that that: if addrinfo[1] == socket.SOCK_STREAM: never validate true as addrinfo[1] = 0

-------------------------
After replacing with the following 3 statements
hostname = tmphostname
url = tmpurl
print hostname, url, addrinfos

The system tries to load data, but ended without any streaming data
Below is the log data:
------------------------
15:22:22 T:10032  NOTICE: Thread LanguageInvoker start, auto delete: false
15:22:22 T:10032  NOTICE: -->Python Interpreter Initialized<--
15:22:22 T:10032 WARNING: Attempt to use invalid handle -1
15:22:23 T:10032  NOTICE: ak.live.cntv.cn
15:22:23 T:10032  NOTICE: http://ak.live.cntv.cn/i/cctv1_1@108430/master.m3u8?b=300-500&AUTH=ip%3D42.60.118.240%7Est%3D1424589442%7Eexp%3D1424675842%7Eacl%3D%2F*%7Ehmac%3Dd2aed1fdc064ed51982474b8fd689e9158de66aad681065a27b66be2ae3c4af3
15:22:23 T:10032  NOTICE: [(2, 0, 0, '', ('125.56.199.120', 80)), (2, 0, 0, '', ('125.56.199.98', 80))]
15:22:23 T:10032  NOTICE: Loading URL http://ak.live.cntv.cn/i/cctv1_1@108430/master.m3u8?b=300-500&AUTH=ip%3D42.60.118.240%7Est%3D1424589442%7Eexp%3D1424675842%7Eacl%3D%2F*%7Ehmac%3Dd2aed1fdc064ed51982474b8fd689e9158de66aad681065a27b66be2ae3c4af3
15:22:23 T:10032  NOTICE: Got AUTH ip=42.60.118.240~st=1424589442~exp=1424675842~acl=/*~hmac=d2aed1fdc064ed51982474b8fd689e9158de66aad681065a27b66be2ae3c4af3
15:22:23 T:10032  NOTICE: Built URL http://ak.live.cntv.cn/i/cctv1_1@108430/master.m3u8?b=300-500&AUTH=ip%3D42.60.118.240%7Est%3D1424589442%7Eexp%3D1424675842%7Eacl%3D%2F*%7Ehmac%3Dd2aed1fdc064ed51982474b8fd689e9158de66aad681065a27b66be2ae3c4af3|Host=ak.live.cntv.cn&Cookie=AUTH%3Dip%3D42.60.118.240%7Est%3D1424589442%7Eexp%3D1424675842%7Eacl%3D%2F%2A%7Ehmac%3Dd2aed1fdc064ed51982474b8fd689e9158de66aad681065a27b66be2ae3c4af3
15:22:24 T:5928  NOTICE: Thread GUIDialogCache start, auto delete: true
15:22:24 T:8328   ERROR: CCurlFile::Stat - Failed: HTTP response code said error(22) for http://ak.live.cntv.cn/i/cctv1_1@108430/master.m3u8?b=300-500&AUTH=ip%3D42.60.118.240%7Est%3D1424589442%7Eexp%3D1424675842%7Eacl%3D%2F*%7Ehmac%3Dd2aed1fdc064ed51982474b8fd689e9158de66aad681065a27b66be2ae3c4af3|Host=ak.live.cntv.cn&Cookie=AUTH%3Dip%3D42.60.118.240%7Est%3D1424589442%7Eexp%3D1424675842%7Eacl%3D%2F%2A%7Ehmac%3Dd2aed1fdc064ed51982474b8fd689e9158de66aad681065a27b66be2ae3c4af3
15:22:24 T:8328  NOTICE: DVDPlayer: Opening: http://ak.live.cntv.cn/i/cctv1_1@108430/master.m3u8?b=300-500&AUTH=ip%3D42.60.118.240%7Est%3D1424589442%7Eexp%3D1424675842%7Eacl%3D%2F*%7Ehmac%3Dd2aed1fdc064ed51982474b8fd689e9158de66aad681065a27b66be2ae3c4af3|Host=ak.live.cntv.cn&Cookie=AUTH%3Dip%3D42.60.118.240%7Est%3D1424589442%7Eexp%3D1424675842%7Eacl%3D%2F%2A%7Ehmac%3Dd2aed1fdc064ed51982474b8fd689e9158de66aad681065a27b66be2ae3c4af3
15:22:24 T:8328 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
15:22:24 T:8328  NOTICE: DXVA::CProcessorHD::PreInit - The Direct3d device doesn't support DXVA-HD.
15:22:24 T:8328  NOTICE: CWinRenderer::Preinit - could not init DXVA-HD processor - skipping
15:22:24 T:2456  NOTICE: Thread DVDPlayer start, auto delete: false
15:22:24 T:2456  NOTICE: Creating InputStream
15:22:24 T:2456   ERROR: CCurlFile::FillBuffer - Failed: HTTP returned error 400
15:22:24 T:2456  NOTICE: CCurlFile::FillBuffer - Reconnect, (re)try 1
15:22:24 T:2456   ERROR: CCurlFile::FillBuffer - Failed: HTTP returned error 400
15:22:24 T:2456   ERROR: CCurlFile::CReadState::Connect, didn't get any data from stream.
15:22:25 T:2456   ERROR: XFILE::CFileCache::Open - failed to open source <http://ak.live.cntv.cn/i/cctv1_1@108430/master.m3u8?b=300-500&AUTH=ip%3D42.60.118.240%7Est%3D1424589442%7Eexp%3D1424675842%7Eacl%3D%2F*%7Ehmac%3Dd2aed1fdc064ed51982474b8fd689e9158de66aad681065a27b66be2ae3c4af3|Host=ak.live.cntv.cn&Cookie=AUTH%3Dip%3D42.60.118.240%7Est%3D1424589442%7Eexp%3D1424675842%7Eacl%3D%2F%2A%7Ehmac%3Dd2aed1fdc064ed51982474b8fd689e9158de66aad681065a27b66be2ae3c4af3>
15:22:25 T:2456  NOTICE: Creating Demuxer
15:22:25 T:2456   ERROR: CCurlFile::GetCookies - invalid cookie: '#HttpOnly_.google.com.sg	TRUE	/	FALSE	1381624987	N	'
15:22:25 T:2456   ERROR: CCurlFile::GetCookies - invalid cookie: '.google.com	TRUE	/	FALSE	1428885787	PR	'
15:22:25 T:2456   ERROR: CCurlFile::GetCookies - invalid cookie: 'web-play.pptv.com	FALSE	/	FALSE	0	JSESSI	'
15:22:25 T:2456   ERROR: CCurlFile::GetCookies - invalid cookie: 'v.yinyuetai.com	FALSE	/	FALSE	0	JSESSI	'
15:22:25 T:2456   ERROR: CCurlFile::GetCookies - invalid cookie: '#HttpOnly_.google.com	TRUE	/	FALSE	1392518494	N	'
15:22:25 T:2456   ERROR: CCurlFile::GetCookies - invalid cookie: 'v.yinyuetai.com	FALSE	/	FALSE	0	JS	'
15:22:25 T:2456   ERROR: CCurlFile::GetCookies - invalid cookie: '.yinyuetai.com	TRUE	/	FALSE	1411877921	yinyuetai_ui	'
15:22:25 T:2456   ERROR: CCurlFile::GetCookies - invalid cookie: 'www.yinyuetai.com	FALSE	/	FALSE	0	JSESSIO	'
15:22:25 T:2456   ERROR: CCurlFile::GetCookies - invalid cookie: 'web-play.pptv.com	FALSE	/	FALSE	0	JS	'
15:22:25 T:2456   ERROR: CCurlFile::GetCookies - invalid cookie: '.tvbdo.com	TRUE	/	FALSE	1577145000	__cfdui	'
15:22:25 T:2456   ERROR: CCurlFile::GetCookies - invalid cookie: '.sugoideas.com	TRUE	/	FALSE	1577145000	__cfdu	'
15:22:25 T:2456   ERROR: CCurlFile::GetCookies - invalid cookie: 'v.yinyuetai.com	FALSE	/	FALSE	0	JSE	'
15:22:25 T:2456   ERROR: CCurlFile::GetCookies - invalid cookie: 'v.yinyuetai.com	FALSE	/	FALSE	0	JSESS	'
15:22:25 T:2456   ERROR: CCurlFile::GetCookies - invalid cookie: 'pdl.vimeocdn.com	FALSE	/	FALSE	0	aka_d	'
15:22:25 T:2456   ERROR: CCurlFile::GetCookies - invalid cookie: 'web-play.pptv.com	FALSE	/	FALSE	0	JSESS	'
15:22:25 T:2456   ERROR: CCurlFile::GetCookies - invalid cookie: '.sugoideas.com	TRUE	/	FALSE	1577145000	__c	'
15:22:25 T:2456   ERROR: CCurlFile::GetCookies - invalid cookie: 'pdl.vimeocdn.com	FALSE	/	FALSE	0	aka_de	'
15:22:25 T:2456   ERROR: CCurlFile::GetCookies - invalid cookie: '.tvbdo.com	TRUE	/	FALSE	1577145000	_	'
15:22:25 T:2456   ERROR: CCurlFile::GetCookies - invalid cookie: 'om	FALSE	/	FALSE	0	JSE	'
15:22:25 T:2456   ERROR: CCurlFile::GetCookies - invalid cookie: 'web-play.pptv.com	FALSE	/	FALSE	0	JSE	'
15:22:25 T:2456   ERROR: CCurlFile::GetCookies - invalid cookie: '.pOnly_.google.com.sg	TRUE	/	FALSE	1381624987	N	'
15:22:25 T:2456   ERROR: CCurlFile::GetCookies - invalid cookie: 'SE	FALSE	/	FALSE	0	JSE	'
15:22:25 T:2456   ERROR: CCurlFile::GetCookies - invalid cookie: 'pdl.vimeocdn.com	FALSE	/	FALSE	0	aka_	'
15:22:25 T:2456   ERROR: CCurlFile::GetCookies - invalid cookie: '.sugoideas.com	TRUE	/	FALSE	1577145000	__cfd	'
15:22:25 T:2456   ERROR: CCurlFile::GetCookies - invalid cookie: '.tvbdo.com	TRUE	/	FALSE	1577145000	__c	'
15:22:25 T:2456   ERROR: CCurlFile::GetCookies - invalid cookie: 'pdl.vimeocdn.com	FALSE	/	FALSE	0	aka	'
15:22:25 T:2456   ERROR: CCurlFile::GetCookies - invalid cookie: 'ALSE	FALSE	/	FALSE	0	JSE	'
15:22:25 T:2456   ERROR: CCurlFile::GetCookies - invalid cookie: 'FALSE	FALSE	/	FALSE	0	JSE	'
15:22:25 T:2456   ERROR: CCurlFile::GetCookies - invalid cookie: 'web-play.pptv.com	FALSE	/	FALSE	0	JSESSIONI	'
15:22:25 T:2456   ERROR: CCurlFile::GetCookies - invalid cookie: 'web-play.pptv.com	FALSE	/	FALSE	0	J	'
15:22:25 T:2456   ERROR: CCurlFile::GetCookies - invalid cookie: '.yinyuetai.com	TRUE	/	FALSE	1411877921	yinyuetai_	'
15:22:25 T:2456   ERROR: CCurlFile::GetCookies - invalid cookie: '.google.com	TRUE	/	FALSE	1428885787	PRE	'
15:22:25 T:2456   ERROR: CCurlFile::GetCookies - invalid cookie: 'SE	FALSE	/	FALSE	0	J	'
15:22:25 T:2456   ERROR: CCurlFile::GetCookies - invalid cookie: 'pdl.vimeocdn.com	FALSE	/	FALSE	0	a	'
15:22:25 T:2456   ERROR: CCurlFile::GetCookies - invalid cookie: '.yinyuetai.com	TRUE	/	FALSE	1411877921	y	'
15:22:25 T:2456   ERROR: CCurlFile::GetCookies - invalid cookie: 'ay.pptv.com	FALSE	/	FALSE	0	J	'
15:22:25 T:2456   ERROR: CCurlFile::GetCookies - invalid cookie: 'om	FALSE	/	FALSE	0	aka	'
15:22:25 T:2456   ERROR: CCurlFile::GetCookies - invalid cookie: '.google.com	TRUE	/	FALSE	1428885787	P	'
15:22:25 T:2456   ERROR: CCurlFile::GetCookies - invalid cookie: 'www.yinyuetai.com	FALSE	/	FALSE	0	JS	'
15:22:25 T:2456   ERROR: CCurlFile::GetCookies - invalid cookie: 'pdl.vimeocdn.com	FALSE	/	FALSE	0	ak	'
15:22:26 T:2456   ERROR: CCurlFile::GetCookies - invalid cookie: '.oogle.com	TRUE	/	FALSE	1392518494	N	'
15:22:26 T:2456   ERROR: CCurlFile::GetCookies - invalid cookie: 'RUE	FALSE	/	FALSE	1428885787	PRE	'
15:22:26 T:2456   ERROR: CCurlFile::GetCookies - invalid cookie: '.yinyuetai.com	TRUE	/	FALSE	1411877921	yinyueta	'
15:22:26 T:2456   ERROR: CCurlFile::GetCookies - invalid cookie: '.sugoideas.com	TRUE	/	FALSE	1577145000	__	'
15:22:26 T:2456   ERROR: CCurlFile::GetCookies - invalid cookie: 'E	FALSE	/	FALSE	1411877921	yinyueta	'
15:22:26 T:2456   ERROR: CCurlFile::GetCookies - invalid cookie: 'E	FALSE	/	FALSE	1411877921	yiny	'
15:22:26 T:2456   ERROR: CCurlFile::GetCookies - invalid cookie: '#HttpOnly_.on99.sx	TRUE	/	FALSE	1577145000	_	'
15:22:26 T:2456   ERROR: CCurlFile::GetCookies - invalid cookie: '.google.com.sg	TRUE	/	FALSE	1460411523	PR	'
15:22:26 T:2456   ERROR: CCurlFile::GetCookies - invalid cookie: '.yinyuetai.com	TRUE	/	FALSE	1411877921	yinyuetai	'
15:22:26 T:2456   ERROR: CCurlFile::GetCookies - invalid cookie: '.ak.live.cntv.cn	TRUE	/i/cctv2_1@139970/	FALSE	0	_alid	'
15:22:26 T:2456   ERROR: CCurlFile::GetCookies - invalid cookie: 'E	FALSE	/	FALSE	1411877921	y	'
15:22:26 T:2456   ERROR: CCurlFile::GetCookies - invalid cookie: 'v.yinyuetai.com	FALSE	/	FALSE	0	J	'
15:22:26 T:2456   ERROR: CDVDPlayer::OpenDemuxStream - Error creating demuxer
15:22:26 T:2456  NOTICE: CDVDPlayer::OnExit()
15:22:26 T:8328  NOTICE: CDVDPlayer::CloseFile()
15:22:26 T:8328  NOTICE: DVDPlayer: waiting for threads to exit
15:22:26 T:8328  NOTICE: DVDPlayer: finished waiting
15:22:26 T:8328  NOTICE: CDVDPlayer::CloseFile()
15:22:26 T:8328  NOTICE: DVDPlayer: waiting for threads to exit
15:22:26 T:8328  NOTICE: DVDPlayer: finished waiting

**Comment by RunasSudo** [comment]
That's very strange. The CNTV server seems to be responding with a 400 (Bad Request) error code, which it shouldn't be doing...

Can you view CCTV1 from the [CNTV website](http://tv.cntv.cn/live/cctv1)? If you have an iOS device (or can make your browser spoof an iOS User-Agent), can you try watching CCTV1 from the CNTV website on iOS?

**Comment by cmeng-git** [comment]
If i change to the following code immediately after "if jsondata.has_key("hls_url"):" to the following,
either with hls4 or hls3 link; I am able to watch CCTV1 on Kodi player.
But the link seems to have timeout constraints; some time the video show the link has expired (in Chinese)

-------------------
			if jsondata.has_key("hls_url"):
				if jsondata["hls_url"].has_key("hls4"):
					p_url = jsondata["hls_url"]["hls4"]
					xbmc.Player().play(p_url)
				return

**Comment by RunasSudo** [comment]
Yes, it is necessary to extract the AUTH parameter from the URL and pass it in as a Cookie to prevent that. I don't understand how that would cause the request to be malformed, though...

**Comment by cmeng-git** [comment]
The video playback does not does not last long, it gets cut off after about a short period of playback, say few tens of seconds

**Comment by cmeng-git** [comment]
I will take a look at other time and see if I can find the problem. But why if addrinfo[1] == socket.SOCK_STREAM: did not validated true.

**Comment by RunasSudo** [comment]
The addrinfo[1] issue may just be a platform-dependent issue. It's not necessary, and that entire section can be removed as I described earlier. The video playback being cut off is caused by the absence of:

    auth = urlparse.parse_qs(urlparse.urlparse(url)[4])["AUTH"][0]
    url = url + "|" + urllib.urlencode( { "Cookie" : "AUTH=" + auth, "Host" : hostname } )

These statements are required before the `xbmc.Player().play(url)` call to prevent the video from stopping after a few seconds.

**Comment by RunasSudo** [comment]
Please continue discussion at RunasSudo/plugin.video.cntv-live#22, so I can keep track of this issue better.

**Comment by cmeng-git** [comment]
Just have a quick check on CNTV plugin again at around 6:20pm local time while the network is not so busy:

Need to comment out the statement as it always failed. (addrinfo[1] = 0 on WIndows 7 xbmc)
# if addrinfo[1] == socket.SOCK_STREAM:

I was able to watch the CCTV1 channel, a couple of minutes (> 4 minutes) before it get disconnected; likely to be caused by socket timeout when server is too busy to stream data.

Found that the following two statement will also cause error when the network is busy, so I usually commented them out during testing. Otherwise it drops straight to ""Channel has no HLS stream"" message when channel is busy.
# conn = urllib2.urlopen(req, timeout=TIMEOUT_S)
# conn.read(8) #Try reading a few bytes

From observation, believe the whole problem observed are likely due to network overloaded, and socket connect attempts always failed.

I have experienced similar network timeout in other xbmc plugins that I have developed, so I usually give many trials (5 times) before giving up. YinYueTai on ugc playback is a good example.

You may have to do the same, when trying to connect to the streaming server.

**Pull request merged**
