### PR TITLE
Update plugin.video.bdyun to v0.1.3

### PR DESCRIPTION
**Pull request by caasiu**
Fix plugin.video.bdyun issue [#1](https://github.com/caasiu/plugin.video.bdyun/issues/1)

### CODE REVIEW

**Comment by taxigps** [comment]
why close this?

**Comment by caasiu** [comment]
I made this pull request with impulsion.
Version 0.1.1 still has some issue.
Now the stable version is v0.1.3, but the PR title is v0.1.1, so I have to close it.
I will commit v0.1.3 within these day.
I'm sorry making this mistake.

**Comment by caasiu** [comment]
Should I make another PR?

**Comment by jindaxia** [comment]
no need to open another pr,

**Comment by caasiu** [comment]
I open another PR #115 .
sorry for inconvenience.

**Pull request closed without merging**
